# This file was generated by GoReleaser. DO NOT EDIT.
cask "glean-cli" do
  name "glean-cli"
  desc "CLI for Glean.com APIs - search documents and run agents"
  homepage "https://github.com/sebastian-kollmann/glean-cli"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glean-cli"

  on_macos do
    on_intel do
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v#{version}/glean_#{version}_darwin_amd64.tar.gz"
      sha256 "f0f3529c1b37d053ec0c46bb3ce08147bbb46893f09c75b65be94a819fbedfef"
    end
    on_arm do
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v#{version}/glean_#{version}_darwin_arm64.tar.gz"
      sha256 "c7de4dac990968a5defa5332e069b06e4b39252cb4589691fe8adfac07e523c3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v#{version}/glean_#{version}_linux_amd64.tar.gz"
      sha256 "c0bed1debf500f1afa8f41f21ba860502d710303b832d0d94df58a9470258ad6"
    end
    on_arm do
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v#{version}/glean_#{version}_linux_arm64.tar.gz"
      sha256 "923b3f8c46bcb426882533c4ab7c6088d8a0a7fa63b7cf55e6b37d7626072cc6"
    end
  end

  # No zap stanza required
end
