# This file was generated by GoReleaser. DO NOT EDIT.
cask "glean-cli" do
  name "glean-cli"
  desc "CLI for Glean.com APIs - search documents and run agents"
  homepage "https://github.com/sebastian-kollmann/glean-cli"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glean-cli"

  on_macos do
    on_intel do
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v#{version}/glean_#{version}_darwin_amd64.tar.gz"
      sha256 "161d87c70e1a54388d8bc0b19bfd2d5ec3a35090565b6645eaf586ddd4915025"
    end
    on_arm do
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v#{version}/glean_#{version}_darwin_arm64.tar.gz"
      sha256 "dbba0cec345ebb09317f42faef71c4bbd27cbc04bc69c15cd2d374e7e7c8fd35"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v#{version}/glean_#{version}_linux_amd64.tar.gz"
      sha256 "6574bd804d4853960f7f1f3212d20a0dbfa247ec0b8f13db2cd80a7aad41e08f"
    end
    on_arm do
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v#{version}/glean_#{version}_linux_arm64.tar.gz"
      sha256 "819a1055481a67b12439cbbdf4e2d3deb022d1bf482a5b4960da675ff9161f40"
    end
  end

  # No zap stanza required
end
