# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GleanCli < Formula
  desc "CLI for Glean.com APIs - search documents and run agents"
  homepage "https://github.com/sebastian-kollmann/glean-cli"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v0.0.1/glean_0.0.1_darwin_amd64.tar.gz"
      sha256 "fa3a8caa411e077263d63ff4ded77bbb1b544258e66ff22f8b16d87c24d74245"

      def install
        bin.install "glean"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v0.0.1/glean_0.0.1_darwin_arm64.tar.gz"
      sha256 "6b38fb6642cf66c982619571981dbad4abe217aaec00a0cf379be112b59b413a"

      def install
        bin.install "glean"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v0.0.1/glean_0.0.1_linux_amd64.tar.gz"
      sha256 "6f49bc107199d5bdaef4b4e1d3fcfdbade87215e8402ae014327f5888b3dca5f"
      def install
        bin.install "glean"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v0.0.1/glean_0.0.1_linux_arm64.tar.gz"
      sha256 "858f6d90b1e47c830cb681055822233e4fda41a7d17cb30d1a4830e9e8da0727"
      def install
        bin.install "glean"
      end
    end
  end

  test do
    system "#{bin}/glean", "version"
  end
end
