# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GleanCli < Formula
  desc "CLI for Glean.com APIs - search documents and run agents"
  homepage "https://github.com/sebastian-kollmann/glean-cli"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v0.0.2/glean_0.0.2_darwin_amd64.tar.gz"
      sha256 "f9aea74b8cd0f044ecc6e51434d8175a904c42dbf27f54e273b94f57fe5c2c75"

      def install
        bin.install "glean"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v0.0.2/glean_0.0.2_darwin_arm64.tar.gz"
      sha256 "4c6929ecfffb903d82cbb2dd0b1b03fd4297392cba30e76336f1d16003795da1"

      def install
        bin.install "glean"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v0.0.2/glean_0.0.2_linux_amd64.tar.gz"
      sha256 "119061473c9cfdda8879fcef46f51bdfd6b86ed1b10603ba101396aed62fee35"
      def install
        bin.install "glean"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastian-kollmann/glean-cli/releases/download/v0.0.2/glean_0.0.2_linux_arm64.tar.gz"
      sha256 "7716ee3f1ff5995e2a214132ef9f470ab0b16c610ce83deb245100119b3a8cd9"
      def install
        bin.install "glean"
      end
    end
  end

  test do
    system "#{bin}/glean", "version"
  end
end
